print('Hello and welcome to Space Animator')
print('What is your Name')
Name = input()
print('What character type do you want to be')
Character = input()
print('What is your characters stats. Be aware that you can only have a conbind total number of 100')
print('strength')
strength = input()
print('stealth')
stealth = input()
print('ranged')
ranged = input()
print('magica')
magica = input()
print('crafting')
crafting = input()
print('intelligence')
intelligence = input()
print('Ok' , Name, 'You have chosen' , Character, 'design, your stats are', strength , 'strength, ', stealth , 'stealth, ', ranged , 'ranged, ', magica , 'magica, ', crafting , 'crafting, ', intelligence , 'intelligence, ', 'does this look right')
input()
print('lets begain the game welcome to Space Animator')
